version: '3.4'

services:
  marketstockanalyzer.api:
    image: ${DOCKER_REGISTRY-}marketstockanalyzerapi
    build:
      context: .
      dockerfile: MarketStockAnalyzer.API/Dockerfile
  
  marketstockanalyzer.client:
    image: ${DOCKER_REGISTRY-}marketstockanalyzerclient
    build:
      context: MarketStockAnalyzer.Client/app
      dockerfile: ./Dockerfile
  
  marketstockanalyzer.db:
    image: mongo