apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketstockanalyzerclient-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketstockanalyzerclient
  template:
    metadata:
      labels:
        app: marketstockanalyzerclient
    spec:
      containers:
      - name: marketstockanalyzerclient
        image: marwil665/marketstockanalyzerclient:new18
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_NAME
          value: marketstockanalyzerclient
        - name: marketstockanalyzerapiURL
          valueFrom:
            configMapKeyRef:
              name: marketstockanalyzerapi-configmap
              key: marketstockanalyzerapi_url 
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "4000m"


---
apiVersion: v1
kind: Service
metadata:
  name: marketstockanalyzerclient-service
spec:
  type: LoadBalancer
  selector:
    app: marketstockanalyzerclient
  ports:
  - protocol: TCP
    name: client-port
    port: 3000
    targetPort: 80